// <auto-generated />
using System;
using EasyHouse.Shared.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EasyHouse.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251128072549_AddCurrencyAndPaymentDate")]
    partial class AddCurrencyAndPaymentDate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EasyHouse.IAM.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("first_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("last_name");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.HasKey("UserId");

                    b.ToTable("users", "public");
                });

            modelBuilder.Entity("EasyHouse.Simulations.Domain.Models.Entities.AmortizationDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amortization")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Balance")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Interest")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Payment")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Period")
                        .HasColumnType("integer");

                    b.Property<Guid>("SimulationId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SimulationId");

                    b.ToTable("amortization_details", "public");
                });

            modelBuilder.Entity("EasyHouse.Simulations.Domain.Models.Entities.Client", b =>
                {
                    b.Property<Guid>("ClientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("DocumentNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("MonthlyIncome")
                        .HasColumnType("numeric");

                    b.Property<string>("Occupation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("ClientId");

                    b.HasIndex("UserId");

                    b.ToTable("clients", "public");
                });

            modelBuilder.Entity("EasyHouse.Simulations.Domain.Models.Entities.Config", b =>
                {
                    b.Property<Guid>("ConfigId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal?>("AnnualDiscountRate")
                        .HasColumnType("numeric");

                    b.Property<string>("Capitalization")
                        .HasColumnType("text");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("DisbursementCommission")
                        .HasColumnType("numeric");

                    b.Property<int>("GraceMonths")
                        .HasColumnType("integer");

                    b.Property<string>("GracePeriodType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("HousingBonus")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Itf")
                        .HasColumnType("numeric");

                    b.Property<decimal>("LifeInsurance")
                        .HasColumnType("numeric");

                    b.Property<decimal>("MonthlyFees")
                        .HasColumnType("numeric");

                    b.Property<decimal>("MonthlyMaintenance")
                        .HasColumnType("numeric");

                    b.Property<string>("RateType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("RiskInsurance")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("Tea")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("Tna")
                        .HasColumnType("numeric");

                    b.HasKey("ConfigId");

                    b.ToTable("configs", "public");
                });

            modelBuilder.Entity("EasyHouse.Simulations.Domain.Models.Entities.House", b =>
                {
                    b.Property<Guid>("HouseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal?>("BuiltArea")
                        .HasColumnType("numeric");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<string>("Project")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PropertyCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("TotalArea")
                        .HasColumnType("numeric");

                    b.HasKey("HouseId");

                    b.ToTable("houses", "public");
                });

            modelBuilder.Entity("EasyHouse.Simulations.Domain.Models.Entities.Report", b =>
                {
                    b.Property<Guid>("ReportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("GeneratedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ReportUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("SimulationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("ReportId");

                    b.HasIndex("SimulationId");

                    b.ToTable("reports", "public");
                });

            modelBuilder.Entity("EasyHouse.Simulations.Domain.Models.Entities.Simulation", b =>
                {
                    b.Property<Guid>("SimulationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal?>("AnnualIRR")
                        .HasColumnType("numeric");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConfigId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("DisbursementCommission")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("FixedQuota")
                        .HasColumnType("numeric");

                    b.Property<Guid>("HouseId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("InitialQuota")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("InsuranceMaintenanceFees")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("LoanAmount")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<decimal?>("TCEA")
                        .HasColumnType("numeric");

                    b.Property<int>("TermMonths")
                        .HasColumnType("integer");

                    b.Property<decimal?>("TotalCreditCost")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("TotalInterests")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("VAN")
                        .HasColumnType("numeric");

                    b.HasKey("SimulationId");

                    b.HasIndex("ClientId");

                    b.HasIndex("ConfigId");

                    b.HasIndex("HouseId");

                    b.ToTable("simulations", "public");
                });

            modelBuilder.Entity("EasyHouse.Simulations.Domain.Models.Entities.AmortizationDetail", b =>
                {
                    b.HasOne("EasyHouse.Simulations.Domain.Models.Entities.Simulation", "Simulation")
                        .WithMany("AmortizationSchedule")
                        .HasForeignKey("SimulationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Simulation");
                });

            modelBuilder.Entity("EasyHouse.Simulations.Domain.Models.Entities.Client", b =>
                {
                    b.HasOne("EasyHouse.IAM.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("EasyHouse.Simulations.Domain.Models.Entities.Report", b =>
                {
                    b.HasOne("EasyHouse.Simulations.Domain.Models.Entities.Simulation", "Simulation")
                        .WithMany()
                        .HasForeignKey("SimulationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Simulation");
                });

            modelBuilder.Entity("EasyHouse.Simulations.Domain.Models.Entities.Simulation", b =>
                {
                    b.HasOne("EasyHouse.Simulations.Domain.Models.Entities.Client", "Client")
                        .WithMany("Simulations")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EasyHouse.Simulations.Domain.Models.Entities.Config", "Config")
                        .WithMany("Simulations")
                        .HasForeignKey("ConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EasyHouse.Simulations.Domain.Models.Entities.House", "House")
                        .WithMany("Simulations")
                        .HasForeignKey("HouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Config");

                    b.Navigation("House");
                });

            modelBuilder.Entity("EasyHouse.Simulations.Domain.Models.Entities.Client", b =>
                {
                    b.Navigation("Simulations");
                });

            modelBuilder.Entity("EasyHouse.Simulations.Domain.Models.Entities.Config", b =>
                {
                    b.Navigation("Simulations");
                });

            modelBuilder.Entity("EasyHouse.Simulations.Domain.Models.Entities.House", b =>
                {
                    b.Navigation("Simulations");
                });

            modelBuilder.Entity("EasyHouse.Simulations.Domain.Models.Entities.Simulation", b =>
                {
                    b.Navigation("AmortizationSchedule");
                });
#pragma warning restore 612, 618
        }
    }
}
